# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('title', models.CharField(default=b'', max_length=200)),
                ('type', models.CharField(default=b'', max_length=200)),
                ('episodes', models.IntegerField()),
                ('status', models.CharField(default=b'', max_length=200)),
            ],
        ),
    ]
