# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('num_likes', models.IntegerField(default=0)),
                ('num_dislikes', models.IntegerField(default=-10)),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
