# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20161130_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0),
        ),
    ]
