# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20161201_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='aid',
            field=models.IntegerField(default=0),
        ),
    ]
