# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='normalizedVector',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='average',
            field=models.DecimalField(decimal_places=3, default=7.5, max_digits=5),
        ),
    ]
