# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_member_prefrencevector'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='IDFvector',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
