# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_anime_idfvector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='IDFvector',
        ),
        migrations.AddField(
            model_name='member',
            name='IDFvector',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
