# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20161201_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tagTotal',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
