# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_member_tagtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='normalizedVector',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='IDFvector',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='prefrenceVector',
            field=models.CharField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='tagTotal',
            field=models.CharField(default=b'', max_length=500),
        ),
    ]
