# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20161205_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sid',
            field=models.CharField(default=b'', max_length=10),
        ),
    ]
