# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20161206_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='allTags',
            field=models.CharField(default=b'', max_length=1000),
        ),
    ]
