# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_member_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tolerance',
            field=models.DecimalField(decimal_places=10, default=20, max_digits=15),
        ),
    ]
